title: Landslides: Sliding Your Reality
author: Mahnoor Ahmed
email: m.ahmed-1@student.utwente.nl
description: > # this means to ignore newlines until "baseurl:"
  What are landslides and how are they affecting you? You might not know much, but you have come to the right place.
# social links
twitter_username: notsure
github_username:  mahnoorahmed96

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima 
